import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

import { Navbar } from "@/components/navbar";

const inter = Inter({
	subsets: ["latin"],
	weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
	title: {
		template: "%s | zmeyer.dev",
		default: "zmeyer.dev",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<div className="min-h-screen relative">
						{/* Background with subtle gradient */}
						<div className="fixed inset-0 bg-[#f8f8f8] dark:bg-[#111111] z-0">
							<div className="absolute top-0 right-0 w-1/3 h-1/3 bg-gradient-to-br from-purple-100/40 to-transparent dark:from-purple-900/10 dark:to-transparent rounded-full blur-3xl" />
							<div className="absolute bottom-0 left-0 w-1/2 h-1/2 bg-gradient-to-tr from-blue-100/30 to-transparent dark:from-blue-900/10 dark:to-transparent rounded-full blur-3xl" />
						</div>

						{/* Content */}
						<div className="relative z-10 max-w-4xl mx-auto px-6 py-8">
							<Navbar />
							<main>{children}</main>
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
